sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master
    - next

cache:
  yarn: true

# https://github.com/nodejs/Release#nodejs-release-working-group
matrix:
  include:
    - os: linux
      node_js: "8" # ends December 2019
      env: NO_WATCH_TESTS=1 JOB_PART=test
    - os: linux
      node_js: "7" # no LTS
      env: NO_WATCH_TESTS=1 JOB_PART=test
    - os: linux
      node_js: "6" # ends April 2019
      env: NO_WATCH_TESTS=1 JOB_PART=test
    - os: osx
      node_js: "8"
      env: NO_WATCH_TESTS=1 JOB_PART=test
  allow_failures:
    - os: osx
  fast_finish: true

install:
  - bash ./scripts/travis-install.sh

script: npm run travis:$JOB_PART

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - cat ./coverage/coverage.json | node_modules/codecov.io/bin/codecov.io.js
  - rm -rf ./coverage
