language: node_js
node_js:
  - "6.4.0"
  - "7.5.0"
  - "8.6.0"
before_install:
  - pip install --user codecov
install:
  - npm install
after_success:
  - codecov --file coverage/lcov.info --disable search
cache:
  directories:
    - "node_modules"
