language: node_js
node_js:
  - "8.6.0"
  - "7.5.0"
  - "6.4.0"
before_install:
  - npm install -g npm
  - npm config set spin false
  - npm install -g codecov
install:
  - npm install
cache:
  directories:
    - "node_modules"
