branches:
  only:
    - master
    - next

init:
  - git config --global core.autocrlf input

clone_depth: 50

# https://github.com/nodejs/Release#nodejs-release-working-group
environment:
  matrix:
    - nodejs_version: 8 # ends December 2019
      job_part: test
    - nodejs_version: 7 # no LTS
      job_part: test
    - nodejs_version: 6 # ends April 2019
      job_part: test

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install yarn -g
  - yarn install --frozen-lockfile
  - yarn link --frozen-lockfile || yarn link --frozen-lockfile
  - yarn link rowser --frozen-lockfile

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - yarn --version
  - cmd: npm run appveyor:%job_part%
