branches:
  only:
    - master
    - dev

init:
  - git config --global core.autocrlf input

clone_depth: 50

environment:
  matrix:
    - nodejs_version: 8
      job_part: test
    - nodejs_version: 7
      job_part: test
    - nodejs_version: 6
      job_part: test

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install yarn -g
  - yarn install --frozen-lockfile
  - yarn link --frozen-lockfile || yarn link --frozen-lockfile
  - yarn link rowser --frozen-lockfile

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - yarn --version
  - cmd: npm run appveyor:%job_part%
